name: get version and channel
description: read package.json and return the full version and version-suffix/channel (ex 'beta' if x.y.z-beta.0)

inputs:
  path:
    description: path to the package.json
    required: false
    default: "package.json"

outputs:
  channel:
    description: version channel (ex 'beta' if x.y.z-beta.0 ), if exists in package.json
    value: ${{ steps.action.outputs.channel}}
  version:
    description: full version from package.json
    value: ${{ steps.action.outputs.version}}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install @actions/core
      shell: bash
    - uses: 'src/action.js'
      id: action
      with:
        path: ${{ inputs.path }}
