name: heroku
version: git
summary: Heroku CLI
description: Heroku CLI
grade: stable
confinement: classic
base: core18

apps:
  heroku:
    plugs:
      - home
      - network-bind
      - network

    command: bin/run

architectures:
  - build-on: [amd64, armhf]

parts:
  heroku:
    source: ../
    plugin: dump
    override-pull: |
      echo "start snapcraftctl pull"
      snapcraftctl pull
      echo "done snapcraftctl pull"
      cd project
      ls -al .
      COMMIT_MSG=$(git log --max-count 1 --pretty="format:%s" | awk '{print $1}')
      CLI_VERSION=$(grep \"version\": packages/cli/package.json | head -n 1 | awk '{print $2}' | tr -d \" | tr -d \,)

      echo "COMMIT_MSG"
      echo $COMMIT_MSG
      echo "CLI_VERSION"
      echo $CLI_VERSION

      if test "$COMMIT_MSG" = "v$CLI_VERSION"; then
        echo "Setting snapcraft version to $COMMIT_MSG"
        snapcraftctl set-version $COMMIT_MSG
      fi
    override-build: |
      set -ex

      # install yarn
      sudo apt-get update
      sudo apt-get install -y curl
      curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      sudo apt-get update
      sudo apt-get install -y nodejs yarn

      cd project
      cd packages/cli
      yarn
      yarn pack --filename heroku.tar.gz
      # extract into the SNAPCRAFT_PART_INSTALL directory, but remove
      # the first `project` folder that yarn crates in the archive
      tar xvzf heroku.tar.gz -C $SNAPCRAFT_PART_INSTALL --strip-components=1
      ls -al $SNAPCRAFT_PART_INSTALL
      OS=linux ./scripts/utils/_fetch_node_binary $SNAPCRAFT_PART_INSTALL/bin
      cd $SNAPCRAFT_PART_INSTALL && yarn --prod
      cd $SNAPCRAFT_PART_INSTALL && bin/run -v
      mkdir -p $SNAPCRAFT_PART_INSTALL/hooks
      cat << "EOF" > $SNAPCRAFT_PART_INSTALL/hooks/configure
      #!/bin/sh
      set -e
      export PATH="$SNAP_DATA/bin:$PATH"
      heroku update
      EOF
      cat $SNAPCRAFT_PART_INSTALL/hooks/configure
      chmod +x $SNAPCRAFT_PART_INSTALL/hooks/configure
    override-stage: |
      set -ex
      snapcraftctl stage
      ls -al $SNAPCRAFT_PART_INSTALL
      # using | instead of / for this sed command
      # so we don't have to escape the value of $SNAP
      # which is a path with slashes
      sed -i "s|#!/usr/bin/env node|#!$SNAP/heroku/current/bin node|" $SNAPCRAFT_PART_INSTALL/bin/run
      # sed -i "s/#!\/usr\/bin\/env node/#!$SNAP/heroku/current/bin/node/" $SNAPCRAFT_PART_INSTALL/run
      sed -i "s/^process\.env\.HEROKU_UPDATE_INSTRUCTIONS.*$/process.env.HEROKU_UPDATE_INSTRUCTIONS = 'update with: snap refresh heroku'/" $SNAPCRAFT_PART_INSTALL/bin/run
