name: Update CLI Command DevCenter Documentation

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-devcenter-command-docs:
    name: Update Devcenter command docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install package deps
        run: yarn --immutable --network-timeout 1000000
      - name: Install Devcenter CLI
        run: |
          gem install devcenter
          devcenter help
